### ISSUE TITLE
Image for Swarnamruthaprasana

### ISSUE THREAD

**Issue by keertihegde** [Avadhuta-Technologies/Bhaava-Ayurveda#17]
- [x] Generate an image for 2nd section of the page
- [x] Bottom CTA background image to be changed.

**Comment by keertihegde** [comment]
![Image](https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/assets/98891520/346bd57f-028d-4bcc-b136-acd98f710d20)

**Comment by sharath-avadhutatech** [comment]
1: Another image of baby below

![Image](https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/assets/141726892/13c2a753-016c-4e77-9b93-b4063e9d70a8)

**Comment by sharath-avadhutatech** [comment]
2: Bottom contact us banner imager for all pages


![Image](https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/assets/141726892/476bbeb4-3396-4b38-a247-00fd1b88be8c)
